// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Accounts", testAccounts)
	t.Run("AccountTransactions", testAccountTransactions)
	t.Run("DailyEarnings", testDailyEarnings)
	t.Run("Deposits", testDeposits)
	t.Run("Investments", testInvestments)
	t.Run("LoginInfos", testLoginInfos)
	t.Run("Notifications", testNotifications)
	t.Run("Packages", testPackages)
	t.Run("ReferralPayouts", testReferralPayouts)
	t.Run("SecurityCodes", testSecurityCodes)
	t.Run("Subscriptions", testSubscriptions)
	t.Run("Trades", testTrades)
	t.Run("TradeSchedules", testTradeSchedules)
	t.Run("Transfers", testTransfers)
	t.Run("UserSettings", testUserSettings)
	t.Run("Wallets", testWallets)
	t.Run("WeeklyPayouts", testWeeklyPayouts)
	t.Run("Withdrawals", testWithdrawals)
}

func TestDelete(t *testing.T) {
	t.Run("Accounts", testAccountsDelete)
	t.Run("AccountTransactions", testAccountTransactionsDelete)
	t.Run("DailyEarnings", testDailyEarningsDelete)
	t.Run("Deposits", testDepositsDelete)
	t.Run("Investments", testInvestmentsDelete)
	t.Run("LoginInfos", testLoginInfosDelete)
	t.Run("Notifications", testNotificationsDelete)
	t.Run("Packages", testPackagesDelete)
	t.Run("ReferralPayouts", testReferralPayoutsDelete)
	t.Run("SecurityCodes", testSecurityCodesDelete)
	t.Run("Subscriptions", testSubscriptionsDelete)
	t.Run("Trades", testTradesDelete)
	t.Run("TradeSchedules", testTradeSchedulesDelete)
	t.Run("Transfers", testTransfersDelete)
	t.Run("UserSettings", testUserSettingsDelete)
	t.Run("Wallets", testWalletsDelete)
	t.Run("WeeklyPayouts", testWeeklyPayoutsDelete)
	t.Run("Withdrawals", testWithdrawalsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Accounts", testAccountsQueryDeleteAll)
	t.Run("AccountTransactions", testAccountTransactionsQueryDeleteAll)
	t.Run("DailyEarnings", testDailyEarningsQueryDeleteAll)
	t.Run("Deposits", testDepositsQueryDeleteAll)
	t.Run("Investments", testInvestmentsQueryDeleteAll)
	t.Run("LoginInfos", testLoginInfosQueryDeleteAll)
	t.Run("Notifications", testNotificationsQueryDeleteAll)
	t.Run("Packages", testPackagesQueryDeleteAll)
	t.Run("ReferralPayouts", testReferralPayoutsQueryDeleteAll)
	t.Run("SecurityCodes", testSecurityCodesQueryDeleteAll)
	t.Run("Subscriptions", testSubscriptionsQueryDeleteAll)
	t.Run("Trades", testTradesQueryDeleteAll)
	t.Run("TradeSchedules", testTradeSchedulesQueryDeleteAll)
	t.Run("Transfers", testTransfersQueryDeleteAll)
	t.Run("UserSettings", testUserSettingsQueryDeleteAll)
	t.Run("Wallets", testWalletsQueryDeleteAll)
	t.Run("WeeklyPayouts", testWeeklyPayoutsQueryDeleteAll)
	t.Run("Withdrawals", testWithdrawalsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Accounts", testAccountsSliceDeleteAll)
	t.Run("AccountTransactions", testAccountTransactionsSliceDeleteAll)
	t.Run("DailyEarnings", testDailyEarningsSliceDeleteAll)
	t.Run("Deposits", testDepositsSliceDeleteAll)
	t.Run("Investments", testInvestmentsSliceDeleteAll)
	t.Run("LoginInfos", testLoginInfosSliceDeleteAll)
	t.Run("Notifications", testNotificationsSliceDeleteAll)
	t.Run("Packages", testPackagesSliceDeleteAll)
	t.Run("ReferralPayouts", testReferralPayoutsSliceDeleteAll)
	t.Run("SecurityCodes", testSecurityCodesSliceDeleteAll)
	t.Run("Subscriptions", testSubscriptionsSliceDeleteAll)
	t.Run("Trades", testTradesSliceDeleteAll)
	t.Run("TradeSchedules", testTradeSchedulesSliceDeleteAll)
	t.Run("Transfers", testTransfersSliceDeleteAll)
	t.Run("UserSettings", testUserSettingsSliceDeleteAll)
	t.Run("Wallets", testWalletsSliceDeleteAll)
	t.Run("WeeklyPayouts", testWeeklyPayoutsSliceDeleteAll)
	t.Run("Withdrawals", testWithdrawalsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Accounts", testAccountsExists)
	t.Run("AccountTransactions", testAccountTransactionsExists)
	t.Run("DailyEarnings", testDailyEarningsExists)
	t.Run("Deposits", testDepositsExists)
	t.Run("Investments", testInvestmentsExists)
	t.Run("LoginInfos", testLoginInfosExists)
	t.Run("Notifications", testNotificationsExists)
	t.Run("Packages", testPackagesExists)
	t.Run("ReferralPayouts", testReferralPayoutsExists)
	t.Run("SecurityCodes", testSecurityCodesExists)
	t.Run("Subscriptions", testSubscriptionsExists)
	t.Run("Trades", testTradesExists)
	t.Run("TradeSchedules", testTradeSchedulesExists)
	t.Run("Transfers", testTransfersExists)
	t.Run("UserSettings", testUserSettingsExists)
	t.Run("Wallets", testWalletsExists)
	t.Run("WeeklyPayouts", testWeeklyPayoutsExists)
	t.Run("Withdrawals", testWithdrawalsExists)
}

func TestFind(t *testing.T) {
	t.Run("Accounts", testAccountsFind)
	t.Run("AccountTransactions", testAccountTransactionsFind)
	t.Run("DailyEarnings", testDailyEarningsFind)
	t.Run("Deposits", testDepositsFind)
	t.Run("Investments", testInvestmentsFind)
	t.Run("LoginInfos", testLoginInfosFind)
	t.Run("Notifications", testNotificationsFind)
	t.Run("Packages", testPackagesFind)
	t.Run("ReferralPayouts", testReferralPayoutsFind)
	t.Run("SecurityCodes", testSecurityCodesFind)
	t.Run("Subscriptions", testSubscriptionsFind)
	t.Run("Trades", testTradesFind)
	t.Run("TradeSchedules", testTradeSchedulesFind)
	t.Run("Transfers", testTransfersFind)
	t.Run("UserSettings", testUserSettingsFind)
	t.Run("Wallets", testWalletsFind)
	t.Run("WeeklyPayouts", testWeeklyPayoutsFind)
	t.Run("Withdrawals", testWithdrawalsFind)
}

func TestBind(t *testing.T) {
	t.Run("Accounts", testAccountsBind)
	t.Run("AccountTransactions", testAccountTransactionsBind)
	t.Run("DailyEarnings", testDailyEarningsBind)
	t.Run("Deposits", testDepositsBind)
	t.Run("Investments", testInvestmentsBind)
	t.Run("LoginInfos", testLoginInfosBind)
	t.Run("Notifications", testNotificationsBind)
	t.Run("Packages", testPackagesBind)
	t.Run("ReferralPayouts", testReferralPayoutsBind)
	t.Run("SecurityCodes", testSecurityCodesBind)
	t.Run("Subscriptions", testSubscriptionsBind)
	t.Run("Trades", testTradesBind)
	t.Run("TradeSchedules", testTradeSchedulesBind)
	t.Run("Transfers", testTransfersBind)
	t.Run("UserSettings", testUserSettingsBind)
	t.Run("Wallets", testWalletsBind)
	t.Run("WeeklyPayouts", testWeeklyPayoutsBind)
	t.Run("Withdrawals", testWithdrawalsBind)
}

func TestOne(t *testing.T) {
	t.Run("Accounts", testAccountsOne)
	t.Run("AccountTransactions", testAccountTransactionsOne)
	t.Run("DailyEarnings", testDailyEarningsOne)
	t.Run("Deposits", testDepositsOne)
	t.Run("Investments", testInvestmentsOne)
	t.Run("LoginInfos", testLoginInfosOne)
	t.Run("Notifications", testNotificationsOne)
	t.Run("Packages", testPackagesOne)
	t.Run("ReferralPayouts", testReferralPayoutsOne)
	t.Run("SecurityCodes", testSecurityCodesOne)
	t.Run("Subscriptions", testSubscriptionsOne)
	t.Run("Trades", testTradesOne)
	t.Run("TradeSchedules", testTradeSchedulesOne)
	t.Run("Transfers", testTransfersOne)
	t.Run("UserSettings", testUserSettingsOne)
	t.Run("Wallets", testWalletsOne)
	t.Run("WeeklyPayouts", testWeeklyPayoutsOne)
	t.Run("Withdrawals", testWithdrawalsOne)
}

func TestAll(t *testing.T) {
	t.Run("Accounts", testAccountsAll)
	t.Run("AccountTransactions", testAccountTransactionsAll)
	t.Run("DailyEarnings", testDailyEarningsAll)
	t.Run("Deposits", testDepositsAll)
	t.Run("Investments", testInvestmentsAll)
	t.Run("LoginInfos", testLoginInfosAll)
	t.Run("Notifications", testNotificationsAll)
	t.Run("Packages", testPackagesAll)
	t.Run("ReferralPayouts", testReferralPayoutsAll)
	t.Run("SecurityCodes", testSecurityCodesAll)
	t.Run("Subscriptions", testSubscriptionsAll)
	t.Run("Trades", testTradesAll)
	t.Run("TradeSchedules", testTradeSchedulesAll)
	t.Run("Transfers", testTransfersAll)
	t.Run("UserSettings", testUserSettingsAll)
	t.Run("Wallets", testWalletsAll)
	t.Run("WeeklyPayouts", testWeeklyPayoutsAll)
	t.Run("Withdrawals", testWithdrawalsAll)
}

func TestCount(t *testing.T) {
	t.Run("Accounts", testAccountsCount)
	t.Run("AccountTransactions", testAccountTransactionsCount)
	t.Run("DailyEarnings", testDailyEarningsCount)
	t.Run("Deposits", testDepositsCount)
	t.Run("Investments", testInvestmentsCount)
	t.Run("LoginInfos", testLoginInfosCount)
	t.Run("Notifications", testNotificationsCount)
	t.Run("Packages", testPackagesCount)
	t.Run("ReferralPayouts", testReferralPayoutsCount)
	t.Run("SecurityCodes", testSecurityCodesCount)
	t.Run("Subscriptions", testSubscriptionsCount)
	t.Run("Trades", testTradesCount)
	t.Run("TradeSchedules", testTradeSchedulesCount)
	t.Run("Transfers", testTransfersCount)
	t.Run("UserSettings", testUserSettingsCount)
	t.Run("Wallets", testWalletsCount)
	t.Run("WeeklyPayouts", testWeeklyPayoutsCount)
	t.Run("Withdrawals", testWithdrawalsCount)
}

func TestInsert(t *testing.T) {
	t.Run("Accounts", testAccountsInsert)
	t.Run("Accounts", testAccountsInsertWhitelist)
	t.Run("AccountTransactions", testAccountTransactionsInsert)
	t.Run("AccountTransactions", testAccountTransactionsInsertWhitelist)
	t.Run("DailyEarnings", testDailyEarningsInsert)
	t.Run("DailyEarnings", testDailyEarningsInsertWhitelist)
	t.Run("Deposits", testDepositsInsert)
	t.Run("Deposits", testDepositsInsertWhitelist)
	t.Run("Investments", testInvestmentsInsert)
	t.Run("Investments", testInvestmentsInsertWhitelist)
	t.Run("LoginInfos", testLoginInfosInsert)
	t.Run("LoginInfos", testLoginInfosInsertWhitelist)
	t.Run("Notifications", testNotificationsInsert)
	t.Run("Notifications", testNotificationsInsertWhitelist)
	t.Run("Packages", testPackagesInsert)
	t.Run("Packages", testPackagesInsertWhitelist)
	t.Run("ReferralPayouts", testReferralPayoutsInsert)
	t.Run("ReferralPayouts", testReferralPayoutsInsertWhitelist)
	t.Run("SecurityCodes", testSecurityCodesInsert)
	t.Run("SecurityCodes", testSecurityCodesInsertWhitelist)
	t.Run("Subscriptions", testSubscriptionsInsert)
	t.Run("Subscriptions", testSubscriptionsInsertWhitelist)
	t.Run("Trades", testTradesInsert)
	t.Run("Trades", testTradesInsertWhitelist)
	t.Run("TradeSchedules", testTradeSchedulesInsert)
	t.Run("TradeSchedules", testTradeSchedulesInsertWhitelist)
	t.Run("Transfers", testTransfersInsert)
	t.Run("Transfers", testTransfersInsertWhitelist)
	t.Run("UserSettings", testUserSettingsInsert)
	t.Run("UserSettings", testUserSettingsInsertWhitelist)
	t.Run("Wallets", testWalletsInsert)
	t.Run("Wallets", testWalletsInsertWhitelist)
	t.Run("WeeklyPayouts", testWeeklyPayoutsInsert)
	t.Run("WeeklyPayouts", testWeeklyPayoutsInsertWhitelist)
	t.Run("Withdrawals", testWithdrawalsInsert)
	t.Run("Withdrawals", testWithdrawalsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AccountTransactionToAccountUsingAccount", testAccountTransactionToOneAccountUsingAccount)
	t.Run("DailyEarningToAccountUsingAccount", testDailyEarningToOneAccountUsingAccount)
	t.Run("DepositToAccountUsingAccount", testDepositToOneAccountUsingAccount)
	t.Run("InvestmentToAccountUsingAccount", testInvestmentToOneAccountUsingAccount)
	t.Run("LoginInfoToAccountUsingAccount", testLoginInfoToOneAccountUsingAccount)
	t.Run("NotificationToAccountUsingAccount", testNotificationToOneAccountUsingAccount)
	t.Run("ReferralPayoutToAccountUsingAccount", testReferralPayoutToOneAccountUsingAccount)
	t.Run("ReferralPayoutToAccountUsingFromAccount", testReferralPayoutToOneAccountUsingFromAccount)
	t.Run("SecurityCodeToAccountUsingAccount", testSecurityCodeToOneAccountUsingAccount)
	t.Run("SubscriptionToAccountUsingAccount", testSubscriptionToOneAccountUsingAccount)
	t.Run("SubscriptionToPackageUsingPackage", testSubscriptionToOnePackageUsingPackage)
	t.Run("TradeToAccountUsingAccount", testTradeToOneAccountUsingAccount)
	t.Run("TradeScheduleToAccountUsingAccount", testTradeScheduleToOneAccountUsingAccount)
	t.Run("TransferToAccountUsingReceiver", testTransferToOneAccountUsingReceiver)
	t.Run("TransferToAccountUsingSender", testTransferToOneAccountUsingSender)
	t.Run("UserSettingToAccountUsingAccount", testUserSettingToOneAccountUsingAccount)
	t.Run("WalletToAccountUsingAccount", testWalletToOneAccountUsingAccount)
	t.Run("WithdrawalToAccountUsingAccount", testWithdrawalToOneAccountUsingAccount)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("AccountToAccountTransactions", testAccountToManyAccountTransactions)
	t.Run("AccountToDailyEarnings", testAccountToManyDailyEarnings)
	t.Run("AccountToDeposits", testAccountToManyDeposits)
	t.Run("AccountToInvestments", testAccountToManyInvestments)
	t.Run("AccountToLoginInfos", testAccountToManyLoginInfos)
	t.Run("AccountToNotifications", testAccountToManyNotifications)
	t.Run("AccountToReferralPayouts", testAccountToManyReferralPayouts)
	t.Run("AccountToFromAccountReferralPayouts", testAccountToManyFromAccountReferralPayouts)
	t.Run("AccountToSecurityCodes", testAccountToManySecurityCodes)
	t.Run("AccountToSubscriptions", testAccountToManySubscriptions)
	t.Run("AccountToTrades", testAccountToManyTrades)
	t.Run("AccountToTradeSchedules", testAccountToManyTradeSchedules)
	t.Run("AccountToReceiverTransfers", testAccountToManyReceiverTransfers)
	t.Run("AccountToSenderTransfers", testAccountToManySenderTransfers)
	t.Run("AccountToUserSettings", testAccountToManyUserSettings)
	t.Run("AccountToWallets", testAccountToManyWallets)
	t.Run("AccountToWithdrawals", testAccountToManyWithdrawals)
	t.Run("PackageToSubscriptions", testPackageToManySubscriptions)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AccountTransactionToAccountUsingAccountTransactions", testAccountTransactionToOneSetOpAccountUsingAccount)
	t.Run("DailyEarningToAccountUsingDailyEarnings", testDailyEarningToOneSetOpAccountUsingAccount)
	t.Run("DepositToAccountUsingDeposits", testDepositToOneSetOpAccountUsingAccount)
	t.Run("InvestmentToAccountUsingInvestments", testInvestmentToOneSetOpAccountUsingAccount)
	t.Run("LoginInfoToAccountUsingLoginInfos", testLoginInfoToOneSetOpAccountUsingAccount)
	t.Run("NotificationToAccountUsingNotifications", testNotificationToOneSetOpAccountUsingAccount)
	t.Run("ReferralPayoutToAccountUsingReferralPayouts", testReferralPayoutToOneSetOpAccountUsingAccount)
	t.Run("ReferralPayoutToAccountUsingFromAccountReferralPayouts", testReferralPayoutToOneSetOpAccountUsingFromAccount)
	t.Run("SecurityCodeToAccountUsingSecurityCodes", testSecurityCodeToOneSetOpAccountUsingAccount)
	t.Run("SubscriptionToAccountUsingSubscriptions", testSubscriptionToOneSetOpAccountUsingAccount)
	t.Run("SubscriptionToPackageUsingSubscriptions", testSubscriptionToOneSetOpPackageUsingPackage)
	t.Run("TradeToAccountUsingTrades", testTradeToOneSetOpAccountUsingAccount)
	t.Run("TradeScheduleToAccountUsingTradeSchedules", testTradeScheduleToOneSetOpAccountUsingAccount)
	t.Run("TransferToAccountUsingReceiverTransfers", testTransferToOneSetOpAccountUsingReceiver)
	t.Run("TransferToAccountUsingSenderTransfers", testTransferToOneSetOpAccountUsingSender)
	t.Run("UserSettingToAccountUsingUserSettings", testUserSettingToOneSetOpAccountUsingAccount)
	t.Run("WalletToAccountUsingWallets", testWalletToOneSetOpAccountUsingAccount)
	t.Run("WithdrawalToAccountUsingWithdrawals", testWithdrawalToOneSetOpAccountUsingAccount)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("AccountToAccountTransactions", testAccountToManyAddOpAccountTransactions)
	t.Run("AccountToDailyEarnings", testAccountToManyAddOpDailyEarnings)
	t.Run("AccountToDeposits", testAccountToManyAddOpDeposits)
	t.Run("AccountToInvestments", testAccountToManyAddOpInvestments)
	t.Run("AccountToLoginInfos", testAccountToManyAddOpLoginInfos)
	t.Run("AccountToNotifications", testAccountToManyAddOpNotifications)
	t.Run("AccountToReferralPayouts", testAccountToManyAddOpReferralPayouts)
	t.Run("AccountToFromAccountReferralPayouts", testAccountToManyAddOpFromAccountReferralPayouts)
	t.Run("AccountToSecurityCodes", testAccountToManyAddOpSecurityCodes)
	t.Run("AccountToSubscriptions", testAccountToManyAddOpSubscriptions)
	t.Run("AccountToTrades", testAccountToManyAddOpTrades)
	t.Run("AccountToTradeSchedules", testAccountToManyAddOpTradeSchedules)
	t.Run("AccountToReceiverTransfers", testAccountToManyAddOpReceiverTransfers)
	t.Run("AccountToSenderTransfers", testAccountToManyAddOpSenderTransfers)
	t.Run("AccountToUserSettings", testAccountToManyAddOpUserSettings)
	t.Run("AccountToWallets", testAccountToManyAddOpWallets)
	t.Run("AccountToWithdrawals", testAccountToManyAddOpWithdrawals)
	t.Run("PackageToSubscriptions", testPackageToManyAddOpSubscriptions)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Accounts", testAccountsReload)
	t.Run("AccountTransactions", testAccountTransactionsReload)
	t.Run("DailyEarnings", testDailyEarningsReload)
	t.Run("Deposits", testDepositsReload)
	t.Run("Investments", testInvestmentsReload)
	t.Run("LoginInfos", testLoginInfosReload)
	t.Run("Notifications", testNotificationsReload)
	t.Run("Packages", testPackagesReload)
	t.Run("ReferralPayouts", testReferralPayoutsReload)
	t.Run("SecurityCodes", testSecurityCodesReload)
	t.Run("Subscriptions", testSubscriptionsReload)
	t.Run("Trades", testTradesReload)
	t.Run("TradeSchedules", testTradeSchedulesReload)
	t.Run("Transfers", testTransfersReload)
	t.Run("UserSettings", testUserSettingsReload)
	t.Run("Wallets", testWalletsReload)
	t.Run("WeeklyPayouts", testWeeklyPayoutsReload)
	t.Run("Withdrawals", testWithdrawalsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Accounts", testAccountsReloadAll)
	t.Run("AccountTransactions", testAccountTransactionsReloadAll)
	t.Run("DailyEarnings", testDailyEarningsReloadAll)
	t.Run("Deposits", testDepositsReloadAll)
	t.Run("Investments", testInvestmentsReloadAll)
	t.Run("LoginInfos", testLoginInfosReloadAll)
	t.Run("Notifications", testNotificationsReloadAll)
	t.Run("Packages", testPackagesReloadAll)
	t.Run("ReferralPayouts", testReferralPayoutsReloadAll)
	t.Run("SecurityCodes", testSecurityCodesReloadAll)
	t.Run("Subscriptions", testSubscriptionsReloadAll)
	t.Run("Trades", testTradesReloadAll)
	t.Run("TradeSchedules", testTradeSchedulesReloadAll)
	t.Run("Transfers", testTransfersReloadAll)
	t.Run("UserSettings", testUserSettingsReloadAll)
	t.Run("Wallets", testWalletsReloadAll)
	t.Run("WeeklyPayouts", testWeeklyPayoutsReloadAll)
	t.Run("Withdrawals", testWithdrawalsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Accounts", testAccountsSelect)
	t.Run("AccountTransactions", testAccountTransactionsSelect)
	t.Run("DailyEarnings", testDailyEarningsSelect)
	t.Run("Deposits", testDepositsSelect)
	t.Run("Investments", testInvestmentsSelect)
	t.Run("LoginInfos", testLoginInfosSelect)
	t.Run("Notifications", testNotificationsSelect)
	t.Run("Packages", testPackagesSelect)
	t.Run("ReferralPayouts", testReferralPayoutsSelect)
	t.Run("SecurityCodes", testSecurityCodesSelect)
	t.Run("Subscriptions", testSubscriptionsSelect)
	t.Run("Trades", testTradesSelect)
	t.Run("TradeSchedules", testTradeSchedulesSelect)
	t.Run("Transfers", testTransfersSelect)
	t.Run("UserSettings", testUserSettingsSelect)
	t.Run("Wallets", testWalletsSelect)
	t.Run("WeeklyPayouts", testWeeklyPayoutsSelect)
	t.Run("Withdrawals", testWithdrawalsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Accounts", testAccountsUpdate)
	t.Run("AccountTransactions", testAccountTransactionsUpdate)
	t.Run("DailyEarnings", testDailyEarningsUpdate)
	t.Run("Deposits", testDepositsUpdate)
	t.Run("Investments", testInvestmentsUpdate)
	t.Run("LoginInfos", testLoginInfosUpdate)
	t.Run("Notifications", testNotificationsUpdate)
	t.Run("Packages", testPackagesUpdate)
	t.Run("ReferralPayouts", testReferralPayoutsUpdate)
	t.Run("SecurityCodes", testSecurityCodesUpdate)
	t.Run("Subscriptions", testSubscriptionsUpdate)
	t.Run("Trades", testTradesUpdate)
	t.Run("TradeSchedules", testTradeSchedulesUpdate)
	t.Run("Transfers", testTransfersUpdate)
	t.Run("UserSettings", testUserSettingsUpdate)
	t.Run("Wallets", testWalletsUpdate)
	t.Run("WeeklyPayouts", testWeeklyPayoutsUpdate)
	t.Run("Withdrawals", testWithdrawalsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Accounts", testAccountsSliceUpdateAll)
	t.Run("AccountTransactions", testAccountTransactionsSliceUpdateAll)
	t.Run("DailyEarnings", testDailyEarningsSliceUpdateAll)
	t.Run("Deposits", testDepositsSliceUpdateAll)
	t.Run("Investments", testInvestmentsSliceUpdateAll)
	t.Run("LoginInfos", testLoginInfosSliceUpdateAll)
	t.Run("Notifications", testNotificationsSliceUpdateAll)
	t.Run("Packages", testPackagesSliceUpdateAll)
	t.Run("ReferralPayouts", testReferralPayoutsSliceUpdateAll)
	t.Run("SecurityCodes", testSecurityCodesSliceUpdateAll)
	t.Run("Subscriptions", testSubscriptionsSliceUpdateAll)
	t.Run("Trades", testTradesSliceUpdateAll)
	t.Run("TradeSchedules", testTradeSchedulesSliceUpdateAll)
	t.Run("Transfers", testTransfersSliceUpdateAll)
	t.Run("UserSettings", testUserSettingsSliceUpdateAll)
	t.Run("Wallets", testWalletsSliceUpdateAll)
	t.Run("WeeklyPayouts", testWeeklyPayoutsSliceUpdateAll)
	t.Run("Withdrawals", testWithdrawalsSliceUpdateAll)
}
