// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account      string
	DailyEarning string
	Deposit      string
	Package      string
	Subscription string
	Transfer     string
	Wallet       string
	Withdrawal   string
}{
	Account:      "account",
	DailyEarning: "daily_earning",
	Deposit:      "deposit",
	Package:      "package",
	Subscription: "subscription",
	Transfer:     "transfer",
	Wallet:       "wallet",
	Withdrawal:   "withdrawal",
}
