// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account            string
	AccountTransaction string
	DailyEarning       string
	Deposit            string
	Investment         string
	Notification       string
	Package            string
	ReferralPayout     string
	Subscription       string
	Trade              string
	TradeSchedule      string
	Transfer           string
	UserSetting        string
	Wallet             string
	WeeklyPayout       string
	Withdrawal         string
}{
	Account:            "account",
	AccountTransaction: "account_transaction",
	DailyEarning:       "daily_earning",
	Deposit:            "deposit",
	Investment:         "investment",
	Notification:       "notification",
	Package:            "package",
	ReferralPayout:     "referral_payout",
	Subscription:       "subscription",
	Trade:              "trade",
	TradeSchedule:      "trade_schedule",
	Transfer:           "transfer",
	UserSetting:        "user_setting",
	Wallet:             "wallet",
	WeeklyPayout:       "weekly_payout",
	Withdrawal:         "withdrawal",
}
