// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDailyEarnings(t *testing.T) {
	t.Parallel()

	query := DailyEarnings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDailyEarningsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailyEarningsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DailyEarnings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailyEarningsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DailyEarningSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailyEarningsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DailyEarningExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DailyEarning exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DailyEarningExists to return true, but got false.")
	}
}

func testDailyEarningsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	dailyEarningFound, err := FindDailyEarning(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if dailyEarningFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDailyEarningsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DailyEarnings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDailyEarningsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DailyEarnings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDailyEarningsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	dailyEarningOne := &DailyEarning{}
	dailyEarningTwo := &DailyEarning{}
	if err = randomize.Struct(seed, dailyEarningOne, dailyEarningDBTypes, false, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}
	if err = randomize.Struct(seed, dailyEarningTwo, dailyEarningDBTypes, false, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dailyEarningOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dailyEarningTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DailyEarnings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDailyEarningsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	dailyEarningOne := &DailyEarning{}
	dailyEarningTwo := &DailyEarning{}
	if err = randomize.Struct(seed, dailyEarningOne, dailyEarningDBTypes, false, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}
	if err = randomize.Struct(seed, dailyEarningTwo, dailyEarningDBTypes, false, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dailyEarningOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dailyEarningTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testDailyEarningsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDailyEarningsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(dailyEarningColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDailyEarningsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDailyEarningsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DailyEarningSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDailyEarningsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DailyEarnings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	dailyEarningDBTypes = map[string]string{`ID`: `character varying`, `Date`: `bigint`, `Amount`: `bigint`, `Percentage`: `integer`, `Principal`: `bigint`}
	_                   = bytes.MinRead
)

func testDailyEarningsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(dailyEarningPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(dailyEarningAllColumns) == len(dailyEarningPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDailyEarningsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(dailyEarningAllColumns) == len(dailyEarningPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DailyEarning{}
	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dailyEarningDBTypes, true, dailyEarningPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(dailyEarningAllColumns, dailyEarningPrimaryKeyColumns) {
		fields = dailyEarningAllColumns
	} else {
		fields = strmangle.SetComplement(
			dailyEarningAllColumns,
			dailyEarningPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DailyEarningSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDailyEarningsUpsert(t *testing.T) {
	t.Parallel()

	if len(dailyEarningAllColumns) == len(dailyEarningPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DailyEarning{}
	if err = randomize.Struct(seed, &o, dailyEarningDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DailyEarning: %s", err)
	}

	count, err := DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, dailyEarningDBTypes, false, dailyEarningPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailyEarning struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DailyEarning: %s", err)
	}

	count, err = DailyEarnings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
