// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("AccountTransactions", testAccountTransactionsUpsert)

	t.Run("Agents", testAgentsUpsert)

	t.Run("Beneficiaries", testBeneficiariesUpsert)

	t.Run("LoginInfos", testLoginInfosUpsert)

	t.Run("Notifications", testNotificationsUpsert)

	t.Run("PaymentLinks", testPaymentLinksUpsert)

	t.Run("SecurityCodes", testSecurityCodesUpsert)

	t.Run("Transactions", testTransactionsUpsert)

	t.Run("TransactionAssignments", testTransactionAssignmentsUpsert)

	t.Run("UserSettings", testUserSettingsUpsert)
}
