// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("DailyEarnings", testDailyEarningsUpsert)

	t.Run("Deposits", testDepositsUpsert)

	t.Run("Packages", testPackagesUpsert)

	t.Run("Subscriptions", testSubscriptionsUpsert)

	t.Run("Transfers", testTransfersUpsert)

	t.Run("Wallets", testWalletsUpsert)

	t.Run("Withdrawals", testWithdrawalsUpsert)
}
