// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTransactionAsignments(t *testing.T) {
	t.Parallel()

	query := TransactionAsignments()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTransactionAsignmentsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionAsignmentsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TransactionAsignments().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionAsignmentsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TransactionAsignmentSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionAsignmentsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TransactionAsignmentExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TransactionAsignment exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TransactionAsignmentExists to return true, but got false.")
	}
}

func testTransactionAsignmentsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	transactionAsignmentFound, err := FindTransactionAsignment(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if transactionAsignmentFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTransactionAsignmentsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TransactionAsignments().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTransactionAsignmentsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TransactionAsignments().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTransactionAsignmentsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	transactionAsignmentOne := &TransactionAsignment{}
	transactionAsignmentTwo := &TransactionAsignment{}
	if err = randomize.Struct(seed, transactionAsignmentOne, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}
	if err = randomize.Struct(seed, transactionAsignmentTwo, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = transactionAsignmentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = transactionAsignmentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TransactionAsignments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTransactionAsignmentsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	transactionAsignmentOne := &TransactionAsignment{}
	transactionAsignmentTwo := &TransactionAsignment{}
	if err = randomize.Struct(seed, transactionAsignmentOne, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}
	if err = randomize.Struct(seed, transactionAsignmentTwo, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = transactionAsignmentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = transactionAsignmentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testTransactionAsignmentsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTransactionAsignmentsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(transactionAsignmentColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTransactionAsignmentToOneAgentUsingAgent(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TransactionAsignment
	var foreign Agent

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, agentDBTypes, false, agentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Agent struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.AgentID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Agent().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := TransactionAsignmentSlice{&local}
	if err = local.L.LoadAgent(ctx, tx, false, (*[]*TransactionAsignment)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Agent == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Agent = nil
	if err = local.L.LoadAgent(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Agent == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testTransactionAsignmentToOneTransactionUsingTransaction(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TransactionAsignment
	var foreign Transaction

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, transactionAsignmentDBTypes, false, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, transactionDBTypes, false, transactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Transaction struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TransactionID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Transaction().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := TransactionAsignmentSlice{&local}
	if err = local.L.LoadTransaction(ctx, tx, false, (*[]*TransactionAsignment)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Transaction == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Transaction = nil
	if err = local.L.LoadTransaction(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Transaction == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testTransactionAsignmentToOneSetOpAgentUsingAgent(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TransactionAsignment
	var b, c Agent

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, transactionAsignmentDBTypes, false, strmangle.SetComplement(transactionAsignmentPrimaryKeyColumns, transactionAsignmentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, agentDBTypes, false, strmangle.SetComplement(agentPrimaryKeyColumns, agentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, agentDBTypes, false, strmangle.SetComplement(agentPrimaryKeyColumns, agentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Agent{&b, &c} {
		err = a.SetAgent(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Agent != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TransactionAsignments[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.AgentID != x.ID {
			t.Error("foreign key was wrong value", a.AgentID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AgentID))
		reflect.Indirect(reflect.ValueOf(&a.AgentID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.AgentID != x.ID {
			t.Error("foreign key was wrong value", a.AgentID, x.ID)
		}
	}
}
func testTransactionAsignmentToOneSetOpTransactionUsingTransaction(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TransactionAsignment
	var b, c Transaction

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, transactionAsignmentDBTypes, false, strmangle.SetComplement(transactionAsignmentPrimaryKeyColumns, transactionAsignmentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Transaction{&b, &c} {
		err = a.SetTransaction(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Transaction != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TransactionAsignments[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TransactionID != x.ID {
			t.Error("foreign key was wrong value", a.TransactionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TransactionID))
		reflect.Indirect(reflect.ValueOf(&a.TransactionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TransactionID != x.ID {
			t.Error("foreign key was wrong value", a.TransactionID, x.ID)
		}
	}
}

func testTransactionAsignmentsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTransactionAsignmentsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TransactionAsignmentSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTransactionAsignmentsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TransactionAsignments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	transactionAsignmentDBTypes = map[string]string{`ID`: `integer`, `AgentID`: `integer`, `TransactionID`: `uuid`, `Amount`: `bigint`, `Date`: `bigint`, `Status`: `integer`}
	_                           = bytes.MinRead
)

func testTransactionAsignmentsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(transactionAsignmentPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(transactionAsignmentAllColumns) == len(transactionAsignmentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTransactionAsignmentsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(transactionAsignmentAllColumns) == len(transactionAsignmentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TransactionAsignment{}
	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, transactionAsignmentDBTypes, true, transactionAsignmentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(transactionAsignmentAllColumns, transactionAsignmentPrimaryKeyColumns) {
		fields = transactionAsignmentAllColumns
	} else {
		fields = strmangle.SetComplement(
			transactionAsignmentAllColumns,
			transactionAsignmentPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TransactionAsignmentSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTransactionAsignmentsUpsert(t *testing.T) {
	t.Parallel()

	if len(transactionAsignmentAllColumns) == len(transactionAsignmentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TransactionAsignment{}
	if err = randomize.Struct(seed, &o, transactionAsignmentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TransactionAsignment: %s", err)
	}

	count, err := TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, transactionAsignmentDBTypes, false, transactionAsignmentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionAsignment struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TransactionAsignment: %s", err)
	}

	count, err = TransactionAsignments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
