[psql]
    dbname = "mtradas"
    host = "localhost"
    user = "postgres"
    pass = ""
    sslmode = "disable"
    whitelist=[
        "account",
        "account_transaction",
        "notification",
        "user_setting",
        "login_info",
        "security_code",
        "transaction",
        "payment_link",
        "beneficiary"
    ]
